const prompts = [
"Draw a pony standing still/Draw a pony posing",
"Draw a pony movin'/Draw a pony groovin",
"Draw a pony in the snow/Draw a pony bundled up",
"Draw a pony stepping up/Draw a pony looking down",
"Draw a pony wrapping up Autumn/Draw a pony falling",
"Draw a Pony Legend/ A Pony Larger Than Life",
"Draw a pony taking a break/Draw a pony settling down",
"Draw a pony caroling/Draw a pony spreading cheer",
"Draw a pony skiing/Draw a pony winter game",
"Draw a pony decorating/Draw a pony wrapping",
"Draw a pony stretching/Draw a pony on thin ice",
"Draw a pony by the hearth/Draw a pony enjoying cocoa",
"Draw a pony traveling/Draw a pony family",
"Draw a pony celebrating/Draw a triumphant pony",
"Draw any previous theme/Draw every previous theme",
"Draw a pony keeping still/draw a pony holding tight",
"Draw a pony moving/Draw a pony shaking",
"Draw a pony gearing up/Draw a pony packing",
"Draw a pony shrinking back/Draw a pony growing up",
"Draw a pony in disguise/Draw a pony faker",
"Draw a pony playing games/Draw a pony champion",
"Draw a pony at the beach/Draw a pony catching rays",
"Draw a pony cooling off/Draw a pony chilling",
"Draw a pony on a quest/Draw a pony chasing dreams",
"Draw a pony celebrity/Draw a Very Important Pony",
"Draw a pony working out/Draw a pony training",
"Draw a pony back at school/Draw a pony learning",
"Draw a pony helping out/Draw a pony cheering someone on",
"Draw a pony graduating/Draw a pony party",
"Draw a pony standing/draw a pony chilling",
"Draw a pony moving / Draw a pony in action",
"Draw a pony training / draw a pony preparing",
"Draw a pony mending fences / draw a pony fencing",
"Draw a pony in apparel / draw a pony in peril",
"Draw a pony in space / draw a pony spacing out",
"Draw a pony in a vehicle / draw a pony out for a spin",
"Draw a pony as a filly or colt/Draw a tiny pony",
"Draw a video game pony/draw a pony playing a game",
"Draw a pony sleeping/Draw a pony's dream",
"Draw a romantic pony/draw a pony on a date",
"Draw a pony family / Draw a pony traveling",
"Draw a furious pony/draw a pony out of control",
"Draw a sneaky pony/Draw a pony in disguise",
"Draw a pony staying up late/draw a pony in the dark",
"Draw a pony as another species/draw a pony transforming",
"Draw a pony lost at sea/Draw a pony drifting",
"Draw a pony back at school/draw a pony learning",
"Draw an exhausted pony/draw a pony burning out",
"Draw a pony making a decision/draw a pony waffling",
"Draw a pony at the beach/Draw a pony catching rays",
"Draw a pony from or in the future/draw a pony out of time",
"Draw a pony fixing something/draw a pony on the mend",
"Draw a pony searching for something/Draw a pony finding a treasure",
"Draw a surprised pony/draw a pony facing the unexpected",
"Draw a pony in command/Draw a pony filled with confidence",
"Draw a pony doing science/Draw a pony pushing boundaries",
"Draw a pony daredevil/Draw a pony living on the edge",
"Draw a reaping an award/draw a pony at the end of its rope",
"Draw a pony standing / Draw a pony striking a pose",
"Draw a pony in motion / Draw a pony in need of direction",
"Draw a pony warming up / Draw a pony stretching its limits",
"Draw an emotional pony / Draw a pony fit to burst",
"Draw a pony facing the unknown / Draw a pony in the Twilight Zone",
"Draw a pony in mortal peril / Draw a pony steeling themselves",
"Draw a pony modeling / Draw a model pony citizen",
"Draw a pony mingling / Draw a pony blending in",
"Draw a pony in love / Draw a pony crushing on somepony",
"Draw a pony fighting / Draw a pony grappling",
"Draw a pony on a grand adventure / Draw a pony on a personal journey",
"Draw a pony chasing their dreams / Draw a pony reaching for a goal",
"Draw a pony family activity / Draw a pony party",
"Draw a pony crossing over with your favorite game, book, ect / Draw a pony doing something you enjoy",
"Draw a pony as another species / Draw a pony making a change",
"Draw a pony at the beach / Draw a pony soaking up the sun",
"Draw a villainous pony / Draw a misunderstood pony",
"Draw a pony running late / Draw a pony racing the clock",
"Draw a pony showing off their special talent / Draw a pony doing something you wish you could do",
"Draw a pony from or in the future / Draw a pony in space",
"Drawing a pony doing science/drawing a pony pushing boundaries",
"Draw a pony star gazing / Draw a pony being eclipsed",
"Draw an utterly exhausted pony / Draw a pony at wit’s end",
"Draw a pony beating the odds / Draw a pony doing the unexpected",
"Draw a pony doing whatever comes to mind / Draw a pony doing something you’ve never drawn before",
"Draw a primitive pony / Draw a pony going back to nature",
"Draw a pony on the mend / Draw a pony fixing something",
"Draw a pony at school / Draw a pony bursting with knowledge",
"Draw a pony reaching the end / Draw a pony reaching their final destination",
"Draw a pony graduating / Draw a pony party",
"Draw a pony standing / draw a pony frozen in place",
"Draw a pony in action / draw a pony on the run",
"Draw a pony going nuts / draw a pony going batty",
"Draw a pony attaining a goal / draw a pony enjoying the fruits of its labor",
"Draw a pony enjoying a summer treat / draw a pony beating the summer heat",
"Draw a pony as another species / draw a pony transforming their life",
"Draw a pony in danger / draw a pony living life on the edge",
"Draw a pony in love / draw a pony ship(ping)",
"Draw a villainous pony / draw a pony with issues",
"Draw a pony doing something you like to do in real life / Draw a pony doing something they wouldn’t normally do",
"Draw a pony mingling / Draw a pony being a social butterfly",
"Draw a pony family unit / Draw a pony leaving the nest",
"Draw a pony from or in the future / Draw a pony exploring the final frontier",
"Draw a pony crossing over with your favorite game, book, ect / Draw a pony putting on a show",
"Draw a fashionable pony / Draw a pony with good taste",
"Draw a pony facing their darkest fear / Draw a pony during the witching hour",
"Draw a pony on an impossible mission / Draw a pony with the deck stacked against them",
"Draw a pony experiencing a miracle / Draw a pony pulling victory from the jaws of defeat",
"Draw an exhausted pony / Draw a pony out of gas",
"Draw a pony running late / Draw a pony out of time",
"Draw a pony discovering a new culture / Draw a pony with an open mind",
"Draw a pony celebrating your favorite holiday / Draw a pony partying too hard",
"Draw a pony going to school / Draw a pony obtaining forbidden knowledge",
"Draw a pony doing whatever comes to mind / Draw a pony with a brilliant idea",
"Draw a ponified version of a fairy tale / Draw a legendary pony",
"Draw a pony pulling the wool over someone’s eyes / Draw a pony deceiving another",
"Draw a pony with nerves of steel / Draw a pony meeting a goal",
"Draw a pony reaching the end of their journey / Draw a pony meeting their end",
"Redraw an earlier piece from the ATG or if you're a veteran artist redraw one of your early pieces / Draw as many of our prompts as possible in one drawing",
"Draw a pony graduating / Draw a pony starting a new chapter in their life",
"Draw A Pony Standing / A Pony Holding the Line",
"Draw A Mobile Pony / A Pony Showing Off Their Moves",
"Draw A Pony Seeking Guidance / A Pony in Need of Schooling",
"Draw A Pony reaching the breaking point / Draw a broken pony",
"Draw A Pony grasping victory from the jaws of defeat / Draw a pony following their hopes and dreams",
"Draw a boasting pony / Draw making a name for themselves",
"Draw a pony’s darkest secret / Draw a sneaky pony",
"Draw a pony doing something you like to do / Draw your OC’s special talent",
"Draw an episode idea you’ve always wanted in the show / Draw a pony with a bright idea",
"Draw a pony as another species (Draw a MLP species other than an equine) / Draw a pony starting a new life",
"Draw a pony in a pickle / Draw a pony with rotten luck",
"Draw a pony living on the edge / Draw a pony who lost a bet",
"Draw a pony on the wrong side of the law / Draw a villainous pony",
"Draw a lovesick pony / Draw a pony experiencing puppy love",
"Draw a ponyfied version of your favorite book, game, ect / Draw a pony crossing over",
"Draw a pony daydreaming / Draw a pony with their head in the clouds",
"Draw a pony festival / Draw a pony having a night on the town",
"Draw a pony under the weather / Draw a pony not feeling themselves",
"Draw a pony in a dire situation / Draw a pony as the unlikely hero",
"Draw a pony working against the clock / Draw a pony in the nick of time",
"Draw a refreshed pony / Draw a pony on holiday",
"Draw a pony in an artist’s style that inspires you / Draw a pony fanboying/fangirling",
"Draw a pony experiencing your favorite moment in the fandom / Draw a pony experiencing how you discovered FiM for the very first time",
"Draw a pony's greatest fear / Draw a pony meeting their worst nightmare",
"Draw a pony Enjoying Nature / Draw a pony exploring the great outdoors.",
"Draw a pony in control/Draw a pony leading",
"Draw a pony racing to the finish / Draw a pony pushing the limit",
"Draw an exhausted pony / Draw a pony that's run out of juice",
"Draw a pony or ponies doing as many of our past prompts as possible / Draw a pony mixing things up",
"Draw a pony graduating / Draw a pony attaining their goal"
];

function getRandomPrompt() {
  return prompts[Math.floor((Math.random() * prompts.length))];
};

function getTotalPrompts() {
  return prompts.length;
}
